import {
  FaHome,
  FaTools,
  FaMoneyBillAlt,
  FaPrayingHands,
  FaGift,
  FaTshirt,
  FaCoins,
  FaDonate,
  FaLightbulb,
  FaWater,
  FaShoppingCart,
  FaAppleAlt,
  FaCheese,
  FaPepperHot,
  FaCoffee,
  FaTv,
  FaMobileAlt,
  FaGasPump,
  FaSchool,
  FaBook,
  FaPenFancy,
  FaBusAlt,
  FaCar,
  FaParking,
  FaUserMd,
  FaPrescriptionBottleAlt,
  FaHeartbeat,
  FaBriefcaseMedical,
  FaBath,
  FaCut,
  FaSmile,
  FaFilm,
  FaCameraRetro,
  FaBeer,
  FaRedoAlt,
  FaDog,
  FaHouseDamage,
  FaCreditCard,
  FaPlane,
  FaBaby,
  FaDumbbell,
  FaStore,
  FaSeedling,
  FaHandsHelping,
  FaQuestionCircle,
  FaUser,
} from "react-icons/fa";

import { FaBowlFood } from "react-icons/fa6";
export const categoryOptions = [
  {
    value: "Rent/Home Loan EMI",
    label: "Rent/Home Loan EMI",
    icon: FaHome,
  },
  {
    value: "Property Maintenance",
    label: "Property Maintenance",
    icon: FaTools,
  },
  { value: "Property Tax", label: "Property Tax", icon: FaMoneyBillAlt },
  {
    value: "Puja Materials",
    label: "Puja Materials",
    icon: FaPrayingHands,
  },
  {
    value: "Gifts for Relatives",
    label: "Gifts for Relatives",
    icon: FaGift,
  },
  {
    value: "Temple Offerings",
    label: "Temple Offerings",
    icon: FaPrayingHands,
  },
  { value: "Festive Clothing", label: "Festive Clothing", icon: FaTshirt },
  {
    value: "Fixed Deposits (FD)",
    label: "Fixed Deposits (FD)",
    icon: FaCoins,
  },
  {
    value: "Recurring Deposits (RD)",
    label: "Recurring Deposits (RD)",
    icon: FaCoins,
  },
  { value: "Mutual Funds", label: "Mutual Funds", icon: FaCoins },
  { value: "Gold Savings", label: "Gold Savings", icon: FaCoins },
  { value: "Donations", label: "Donations", icon: FaDonate },
  {
    value: "Electricity Bill",
    label: "Electricity Bill",
    icon: FaLightbulb,
  },
  { value: "Water Bill", label: "Water Bill", icon: FaWater },
  { value: "Groceries", label: "Groceries", icon: FaShoppingCart },
  {
    value: "Vegetables & Fruits",
    label: "Vegetables & Fruits",
    icon: FaAppleAlt,
  },
  { value: "Dairy Products", label: "Dairy Products", icon: FaCheese },
  {
    value: "Cooking Oil & Spices",
    label: "Cooking Oil & Spices",
    icon: FaPepperHot,
  },
  {
    value: "Snacks & Beverages",
    label: "Snacks & Beverages",
    icon: FaCoffee,
  },
  {
    value: "Internet & Cable TV",
    label: "Internet & Cable TV",
    icon: FaTv,
  },
  {
    value: "Mobile Phone Bills",
    label: "Mobile Phone Bills",
    icon: FaMobileAlt,
  },
  { value: "Gas Cylinder", label: "Gas Cylinder", icon: FaGasPump },
  { value: "School Fees", label: "School Fees", icon: FaSchool },
  { value: "Tuition Classes", label: "Tuition Classes", icon: FaBook },
  {
    value: "Stationery & Books",
    label: "Stationery & Books",
    icon: FaPenFancy,
  },
  {
    value: "Extracurricular Fees",
    label: "Extracurricular Fees",
    icon: FaBook,
  },
  { value: "Fuel", label: "Fuel", icon: FaGasPump },
  { value: "Public Transport", label: "Public Transport", icon: FaBusAlt },
  {
    value: "Vehicle Maintenance",
    label: "Vehicle Maintenance",
    icon: FaCar,
  },
  { value: "Parking Fees", label: "Parking Fees", icon: FaParking },
  { value: "Doctor Visits", label: "Doctor Visits", icon: FaUserMd },
  { value: "Medicines", label: "Medicines", icon: FaPrescriptionBottleAlt },
  {
    value: "Health Insurance",
    label: "Health Insurance",
    icon: FaHeartbeat,
  },
  {
    value: "Emergency Medical",
    label: "Emergency Medical",
    icon: FaBriefcaseMedical,
  },
  { value: "Toiletries", label: "Toiletries", icon: FaBath },
  { value: "Salon Services", label: "Salon Services", icon: FaCut },
  {
    value: "Clothing & Footwear",
    label: "Clothing & Footwear",
    icon: FaTshirt,
  },
  { value: "Cosmetics", label: "Cosmetics", icon: FaSmile },
  { value: "Movie Outings", label: "Movie Outings", icon: FaFilm },
  { value: "Family Outings", label: "Family Outings", icon: FaCameraRetro },
  { value: "Subscriptions", label: "Subscriptions", icon: FaTv },
  { value: "Dining Out", label: "Dining Out", icon: FaBeer },
  {
    value: "Loan Repayments",
    label: "Loan Repayments",
    icon: FaMoneyBillAlt,
  },
  {
    value: "Unexpected Repairs",
    label: "Unexpected Repairs",
    icon: FaTools,
  },
  { value: "Emergency Fund", label: "Emergency Fund", icon: FaRedoAlt },
  { value: "Household Items", label: "Household Items", icon: FaHome },
  { value: "Pet Care", label: "Pet Care", icon: FaDog },
  {
    value: "Home Renovations",
    label: "Home Renovations",
    icon: FaHouseDamage,
  },
  { value: "Personal Loans", label: "Personal Loans", icon: FaCreditCard },
  {
    value: "Credit Card Payments",
    label: "Credit Card Payments",
    icon: FaCreditCard,
  },
  { value: "Vacation Expenses", label: "Vacation Expenses", icon: FaPlane },
  {
    value: "Childcare Expenses",
    label: "Childcare Expenses",
    icon: FaBaby,
  },
  { value: "Gym Membership", label: "Gym Membership", icon: FaDumbbell },
  {
    value: "Insurance Premiums",
    label: "Insurance Premiums",
    icon: FaHeartbeat,
  },
  { value: "Laundry Services", label: "Laundry Services", icon: FaBath },
  { value: "Online Shopping", label: "Online Shopping", icon: FaStore },
  {
    value: "Fitness Equipments",
    label: "Fitness Equipments",
    icon: FaDumbbell,
  },
  { value: "Home Appliances", label: "Home Appliances", icon: FaTv },
  { value: "Gardening", label: "Gardening", icon: FaSeedling },
  {
    value: "Charity Contributions",
    label: "Charity Contributions",
    icon: FaHandsHelping,
  },
  { value: "Others", label: "Others", icon: FaQuestionCircle },
  { value: "Mahesh", label: "Mahesh", icon: FaUser },
  { value: "Food", label: "Food", icon: FaBowlFood },
];
